### ISSUE TITLE
Добавить пример как пользоваться в VSCode

### ISSUE THREAD

**Issue by nikolai-shabalin** [htmlacademy/linthtml-config-htmlacademy#1]

**Comment by asupstudent** [comment]
Ждем

**Comment by nikolai-shabalin** [comment]
Уже в работе

для того, чтобы заработало придётся перевести расширяемый конфиг в `.linthtmlrc`. Это требование [VS Code расширения](https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-linthtml)

> If you have a valid hmllint configuration file .linthtmlrc (all options available [here](https://github.com/linthtml/linthtml/wiki/Options)) in the current workspace folder the extension will use it. Otherwise, the default configuration of linthtml will be used.


Завтра обсужу с командой и примем решение, что с этим делать

**Comment by nikolai-shabalin** [comment]
Добавил использование в [README.md](https://github.com/htmlacademy/linthtml-config-htmlacademy#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-vs-code)

**Comment by asupstudent** [comment]
Спасибо большое, будем пробовать

**Comment by asupstudent** [comment]
![Screenshot_20230717_200816](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/5c5d34a5-bfce-41cd-8925-89c28e2220d6)
в настройках линтера указано , что нужен отступ в 4 пробела, а в editorconfig (от HTMLAcademy) 2, все красное

**Comment by nikolai-shabalin** [comment]
Можешь показать `package.json`? Хочу посмотреть указанные версии

должны быть вот такие 

```json
{
  "@linthtml/linthtml": "0.9.5",
  "linthtml-config-htmlacademy": "1.0.9",
}
```

> в настройках линтера указано , что нужен отступ в 4 пробела

У нашего линтера нет правил про форматирование. Они все отключены. Скорее всего тебе нужно обновить версию конфига

```bash
npm i linthtml-config-htmlacademy@latest
```


Также я вижу на твоём скриншоте фактические ошибки, которые линтер увидел. Например, в HTML5 не принято закрывать одиночные теги `<meta />`. Правильно `<meta>`. Но можно начать с обновления версии конфига

**Comment by asupstudent** [comment]
[package.zip](https://github.com/htmlacademy/linthtml-config-htmlacademy/files/12072223/package.zip)
Сборка Акселератор - Лига А (использую ее, скоро Акселератор), про стартовый шаблон VSCode понял (эти закрытые одиночные теги оттуда)

**Comment by nikolai-shabalin** [comment]
А ты в итоге обновил версию пакета или уже была обновлена?

В нашем конфиге `'indent-style': false,` отключен совсем. А можешь тогда весь проект zip-архивом скинуть, чтобы я не дёргал тебя по каждому файлу?

**Comment by asupstudent** [comment]
![Screenshot_20230717_203733](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/91df67a7-d967-43a4-945b-5ebf77b86a04)

**Comment by asupstudent** [comment]
Установлена не была, я ее установил начисто

**Comment by nikolai-shabalin** [comment]
Да, я обратил внимание на `indent-style` поэтому и удивляюсь, так как у нас отлючено это правило, как и все остальные про форматирование кода

**Comment by asupstudent** [comment]
Сейчас пришлю

**Comment by nikolai-shabalin** [comment]
Попробуй перезапустить VS Code. Возможно у него в кеше старые настройки ещё

**Comment by asupstudent** [comment]
Ну я это первым делом сделал

**Comment by asupstudent** [comment]
Там в ошибках пишет конкретно про indent-style, и сообщение от linthtml

**Comment by asupstudent** [comment]
[markup.zip](https://github.com/htmlacademy/linthtml-config-htmlacademy/files/12072335/markup.zip)
Разбираю кейсы про сематическую разметку

**Comment by asupstudent** [comment]
https://github.com/asupstudent/markup

**Comment by nikolai-shabalin** [comment]
В `.linthtmlrc` секцию `rules` можешь удалить. Она нужна только если ты сам хочешь переназначить правила

Нужно из 
```json
{
  "extends": "linthtml-config-htmlacademy",
  "rules": {
    "line-max-len": [
      true,
      120
    ]
  }
}
```

сделать

```json
{
  "extends": "linthtml-config-htmlacademy"
}
```

Я бы удалил иначе будет ругаться на все файлы

PS: если что, то это ничего не чинит, поэтому я продолжаю разбираться

**Comment by asupstudent** [comment]
Спасибо, буду пробовать, но получится через несколько дней (уезжаем в поездку). Эта сборка https://github.com/htmlonelove/liga-accelerator-template нашел 5 недочетов в ней

1.  Нужно добавить кастомный синтаксис, иначе VSCode много на чего ругается (например на //)
![e82e79b391c6db3a](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/23107456-65e6-487a-aca8-6e5c405a93f8)

сборка использует его

![Screenshot_20230717_210105](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/a4fd1ab1-4d2c-4f75-b9b8-fe0bd4cc42e7)

2. В файле vendor.js 5 строка лишняя
![5_](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/458d7c49-8763-4829-9b3c-4f18428ca142)

3. Название нужно в нижнем регистре (где name), там под регулярку не подходит VSCode ругается

![34bb92ae02b0ed54](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/8c5b512c-5424-4e8c-a6cf-eca91d7da752)

![Screenshot_20230717_210437](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/310c3350-c800-4f8a-b56d-df7a88dff7ac)

4. В VSCode указал что синтаксис YAML (это не ошибка) иначе ругается на root
![YAML](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/012a99d8-afd6-484c-abdf-d0b2f8535b54)

5. Линтер тоже ругался на eslintconfig.cjs, где кавычки не такие, где чего, вообщем исправил
![eslint_](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/137e9f58-e372-4ed5-be42-6bc25a8f4343)

6. В сборке на грейдировании были задачи на проверку БЭМ дерева + валидация W3C (здесь не включили)

**Comment by asupstudent** [comment]
Я Акселератор перенес (воспользовался этим правом, дома стройка, грейдирование делал в полевых условиях), перенесли на следующий поток 10 октября. Сейчас пока есть время тренируюсь. Выжал на грейдировании 92% и то глупые ошибки, считай опечатки)

**Comment by nikolai-shabalin** [comment]
Все эти недочёты лучше к ним в репозиторий отнести https://github.com/htmlonelove/liga-accelerator-template/issues

Плагин VS Code на самом деле работает. Но он встретил ошибку в нашем linhtml-config и постоянно умирает, поэтому как-то коряво отображает все правила. Я скоро выпущу новую версию и плагин начнёт работать нормально

**Comment by asupstudent** [comment]
Спасибо, буду ждать

**Comment by nikolai-shabalin** [comment]
@asupstudent , мы починили.

Для работоспособности нужно установить последнюю версию конфига

```
npm i -D linthtml-config-htmlacademy@latest
```

В package.json версия конфига должна изменится на `1.0.11`. Выглядит будет вот так
```json
"linthtml-config-htmlacademy": "1.0.11",
```

После этого можно перезапустить VS Code на всяки случай

**Comment by asupstudent** [comment]
Спасибо, буду пробовать

**Comment by asupstudent** [comment]
Заработало, буду детально разбираться
![Screenshot_20230723_142556](https://github.com/htmlacademy/linthtml-config-htmlacademy/assets/37734257/93c0ecca-8d40-45d3-957e-b83264620cff)
Спасибо
